language: node_js
node_js:
    - "8"
    - "7"
    - "6"

install:
    - yarn

before_script:
    - yarn run pretest

script:
    - travis_retry yarn test-travis
    - travis_retry yarn bundlesize

after_success:
    - travis_retry yarn coveralls

after_script:
    - yarn run posttest
